#pragma once

#define CONFIG_LUMIA_LED_CH1_GPIO 0
#define CONFIG_LUMIA_LED_CH2_GPIO 1
#define CONFIG_LUMIA_LED_CH3_GPIO 3
#define CONFIG_LUMIA_LED_CH4_GPIO 7
#define CONFIG_LUMIA_LED_CH5_GPIO 10
#define CONFIG_LUMIA_LED_CH6_GPIO 20
#define CONFIG_LUMIA_LED_CH7_GPIO 21

#define CONFIG_LUMIA_LED_CH1_COUNT 6
#define CONFIG_LUMIA_LED_CH2_COUNT 6
#define CONFIG_LUMIA_LED_CH3_COUNT 6
#define CONFIG_LUMIA_LED_CH4_COUNT 6
#define CONFIG_LUMIA_LED_CH5_COUNT 6
#define CONFIG_LUMIA_LED_CH6_COUNT 6
#define CONFIG_LUMIA_LED_CH7_COUNT 6

#define CONFIG_LUMIA_LED_TX_PHYSICAL_MAX_COUNT 6
#define CONFIG_LUMIA_LED_TX_RESET_US 300

#define CONFIG_LUMIA_SLEEP_SWITCH_GPIO 4
#define CONFIG_LUMIA_SLEEP_SWITCH_ACTIVE_LOW 1
#define CONFIG_LUMIA_SLEEP_SWITCH_DEBOUNCE_MS 30
